version: '2.2'
services:
  config-server:
        container_name: config-server
        build:
            context: .
            dockerfile: Dockerfile-config-server
        image: config-server:latest
        expose:
            - 9090
        ports:
            - 9090:9090
        networks:
            - acc-network
        volumes:
            - config-repo:/var/lib/config-repo
            
  eureka-server:
       container_name: eureka-server
       build:
           context: ./
           dockerfile: Dockerfile.eureka-server
       image: eureka-server:latest
       expose:
           - 8060
       ports:
           - 8060:8060
       networks:
           - acc-network
           
  auth-server:
       container_name: auth-server
       build:
           context: ./
           dockerfile: Dockerfile.auth-server
       image: auth-server:latest
       expose:
           - 8062
       ports:
           - 8062:8062
       networks:
           - acc-network         
                     
  account-server:
       container_name: account-server
       build:
           context: ./
           dockerfile: Dockerfile.account-server
       image: account-server:latest
       environment:
            SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-server:9090"}}}}'
       entrypoint: /opt/bin/account.sh
       expose:
           - 8061
       ports:
           - 8061:8061
       networks:
           - acc-network
       links:
            - config-server:config-server
            - eureka-server:eureka-server
       depends_on:
            - config-server
            - eureka-server
       logging:
            driver: json-file    
           
  gateway-server:          
       container_name: gateway-server
       build:
           context: ./
           dockerfile: Dockerfile.gateway-server
       image: gateway-server:latest
       expose:
           - 8084
       ports:
           - 8084:8084
       networks:
           - acc-network
       links:
            - gateway-server:gateway-server
       depends_on:
            - gateway-server
       logging:
            driver: json-file                      
       
networks:
    acc-network:
        driver: bridge
volumes:
    config-repo:
        external: true        